FROM docker.io/library/ruby:3.3.0

# Rails app lives here
WORKDIR /rails

# Install bundler
RUN gem install bundler

# Copy Gemfiles for dependency caching
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Set up entrypoint
RUN chmod +x /rails/bin/docker-entrypoint

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3001

# Start server bound to all IPs on port 3001 so it is accessible outside container without conflicts
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3001"]
