FROM docker.io/library/ruby:3.4.1

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends libvips-dev

# Rails app lives here
WORKDIR /rails

# Install bundler
RUN gem install bundler

# Copy Gemfiles for dependency caching
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Set up entrypoint
RUN chmod +x /rails/bin/docker-entrypoint

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3002

# Start server bound to all IPs on port 3002 so it is accessible outside container without conflicts
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3002"]
