# App Version Initializer
# - Loads the dynamic version generated by git pre-commit hook

version_file = Rails.root.join("config/version.txt")
APP_VERSION = if File.exist?(version_file)
  File.read(version_file).strip
else
  # Fallback to dev if version file is missing
  "1.0.0.dev"
end
